### ISSUE TITLE
Error: Caught Exception in DataLoader worker process 0

### ISSUE THREAD

**Issue by zhanghming** [hongfz16/DS-Net#6]
Hi, thanks for you excellent work firstly.

I got the error like
```shell
TypeError: Caught TypeError in DataLoader worker process 0.
TypeError: expected dtype object, got 'numpy.dtype[uint8]'
```
when running into the line `for i_iter, inputs in enumerate(val_dataset_loader):` in `cfg_train.py` script, I have googled different solutions but not worked.

Hope you could do me a favor, thanks in advance.

**Comment by hongfz16** [comment]
Hi. Could you please try to locate which line in DataLoader throws the error? Currently, the provided information is not enough for me to help you. I personally have not encountered a similar issue.

**Comment by zhanghming** [comment]
When the code execute [this line](https://github.com/hongfz16/DS-Net/blob/610471fb0ed4256a7941ee5fcf6a69babc5a4b58/dataloader/__init__.py#L77), it cause this problem.

BTW, I have found an solution that to change the `num_worker` from 1 to 0, maybe it refers to the parallel data loader process.

**Comment by hongfz16** [comment]
That's strange. I would expect the TypeError came from somewhere in [this file](https://github.com/hongfz16/DS-Net/blob/main/dataloader/dataset.py). However, if disabling parallel data loading solves the issue, then the problem is not in the DataLoader. Parallel data loading works smoothly in my machine. Maybe it is some weird low-level bug in your machine or the computing power is not enough?

**Comment by zhanghming** [comment]
I'm not the sure what the problem exactly. Thanks for your kindly reply.
